var searchData=
[
  ['l_20interface_20graphique_20strong_0',['&lt;strong&gt;L&apos;interface graphique&lt;/strong&gt;',['../index.html#autotoc_md24',1,'']]],
  ['l_20interface_20graphique_20yanis_20strong_1',['&lt;strong&gt;L&apos;interface graphique [Yanis]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md67',1,'']]],
  ['l_20objectif_2',['L&apos;objectif',['../index.html#autotoc_md1',1,'']]],
  ['l_20objectif_20yanis_20diapo_201_20logo_3',['L&apos;objectif [Yanis] - Diapo 1 (logo)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['la_20balle_20dounia_20strong_4',['&lt;strong&gt;Choisir le type de la balle [Dounia]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['la_20balle_20strong_5',['&lt;strong&gt;Choisir le type de la balle&lt;/strong&gt;',['../index.html#autotoc_md17',1,'']]],
  ['la_20demo_6',['PENDANT LA DEMO',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md84',1,'']]],
  ['la_20demo_20_3a_20vasilis_7',['Compilation [pendant la demo : Vasilis]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md85',1,'']]],
  ['la_20logique_20du_20jeu_20strong_8',['&lt;strong&gt;La logique du jeu&lt;/strong&gt;',['../index.html#autotoc_md23',1,'']]],
  ['la_20musique_20strong_9',['&lt;strong&gt;Changement de la musique&lt;/strong&gt;',['../index.html#autotoc_md18',1,'']]],
  ['la_20musique_20yanis_20strong_10',['&lt;strong&gt;Changement de la musique [Yanis]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['lambda_11',['Fonctions lambda',['../index.html#autotoc_md29',1,'']]],
  ['lambda_20explication_20c_20est_20quoi_20en_20relaite_20def_20suffit_20pas_20dounia_12',['Fonctions lambda + Explication c&apos;est quoi en relaite (def suffit pas) [Dounia]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md72',1,'']]],
  ['lancement_13',['lancement',['../index.html#autotoc_md5',1,'Instructions de lancement'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md87',1,'Instructions de lancement']]],
  ['last_5fhighscore_14',['last_highscore',['../class_game.html#a39428b5c8de846dbdd5efb1be52c9066',1,'Game']]],
  ['last_5fhighscore_5fname_15',['last_highscore_name',['../class_game.html#aeedf815028a7cfc54159f05ee2de7ec4',1,'Game']]],
  ['le_20jeu_16',['Le jeu',['../index.html#autotoc_md2',1,'']]],
  ['le_20jeu_20yanis_20diapo_202_20un_20jue_20lequel_17',['Le jeu [Yanis] - Diapo 2 (Un jue, lequel)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['le_20type_20de_20la_20balle_20dounia_20strong_18',['&lt;strong&gt;Choisir le type de la balle [Dounia]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['le_20type_20de_20la_20balle_20strong_19',['&lt;strong&gt;Choisir le type de la balle&lt;/strong&gt;',['../index.html#autotoc_md17',1,'']]],
  ['lequel_20',['Le jeu [Yanis] - Diapo 2 (Un jue, lequel)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['les_20concepts_20clés_20diapo_206_20strong_21',['&lt;strong&gt;Les concepts clés - Diapo 6&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md66',1,'']]],
  ['les_20différents_20modes_22',['Les différents modes',['../index.html#autotoc_md8',1,'']]],
  ['les_20différents_20modes_20diapo_203_20ou_23',['Les différents modes - Diapo 3 ou +++',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md49',1,'']]],
  ['les_20foncteurs_20strong_24',['&lt;strong&gt;Les foncteurs&lt;/strong&gt;',['../index.html#autotoc_md21',1,'']]],
  ['les_20foncteurs_20vasilis_20strong_25',['&lt;strong&gt;Les foncteurs [Vasilis]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md75',1,'']]],
  ['les_20objets_201_20yanis_202_20dounia_203_20vasilis_20diapo_205_20strong_26',['&lt;strong&gt;Les objets [1. Yanis, 2. Dounia, 3. Vasilis ] - Diapo 5&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md64',1,'']]],
  ['les_20objets_20strong_27',['&lt;strong&gt;Les objets&lt;/strong&gt;',['../index.html#autotoc_md20',1,'']]],
  ['les_20petits_20plus_20diapo_204_28',['Fonctionalites (Les petits plus) - Diapo 4',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['les_20tests_29',['Les tests',['../index.html#autotoc_md33',1,'']]],
  ['letter_30',['Letter',['../class_letter.html',1,'Letter'],['../class_letter.html#ad7d6b89bf521e852dc85cb658a32f653',1,'Letter::Letter(int index, float startX, float startY, float velocity, SDL_Renderer *renderer, TTF_Font *font)']]],
  ['letter_31',['letter',['../class_letter.html#add29e231aa209f890a891ea202dbff4a',1,'Letter']]],
  ['letter_2ecpp_32',['letter.cpp',['../letter_8cpp.html',1,'']]],
  ['letter_2ehpp_33',['letter.hpp',['../letter_8hpp.html',1,'']]],
  ['letter_5ftest_2ecpp_34',['letter_test.cpp',['../letter__test_8cpp.html',1,'']]],
  ['lettersatbottom_35',['lettersAtBottom',['../class_letter.html#a11286b566cff395d9f92b6184ca6bc1f',1,'Letter']]],
  ['load_5fgame_36',['load_game',['../class_saving.html#ab71b9324583e823beda155c1f84ff95d',1,'Saving']]],
  ['load_5fhighscore_37',['load_highscore',['../class_saving.html#aca0f68abac367530e21ec0140ed50cb8',1,'Saving']]],
  ['logic_20strong_38',['logic strong',['../index.html#autotoc_md16',1,'&lt;strong&gt;Game retrieve logic&lt;/strong&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'&lt;strong&gt;Game retrieve logic&lt;/strong&gt;'],['../index.html#autotoc_md15',1,'&lt;strong&gt;Game save logic&lt;/strong&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'&lt;strong&gt;Game save logic&lt;/strong&gt;']]],
  ['logique_20du_20jeu_20strong_39',['&lt;strong&gt;La logique du jeu&lt;/strong&gt;',['../index.html#autotoc_md23',1,'']]],
  ['logo_40',['L&apos;objectif [Yanis] - Diapo 1 (logo)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['loin_41',['Pour aller plus loin',['../index.html#autotoc_md38',1,'']]],
  ['loin_20vasilis_20diapo_208_42',['Pour aller plus loin [Vasilis] - Diapo 8',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md79',1,'']]],
  ['loop_43',['Loop',['../index.html#autotoc_md25',1,'Loop'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md68',1,'Loop']]],
  ['loop_44',['loop',['../class_game.html#a7ad92b77b596d7882a7ae76eb18b5e6c',1,'Game']]]
];
