var searchData=
[
  ['dépendances_0',['Dépendances',['../index.html#autotoc_md7',1,'Dépendances'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md87',1,'Dépendances']]],
  ['développement_1',['Autres aspects du développement',['../index.html#autotoc_md32',1,'']]],
  ['de_20la_20balle_20dounia_20strong_2',['&lt;strong&gt;Choisir le type de la balle [Dounia]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'']]],
  ['de_20la_20balle_20strong_3',['&lt;strong&gt;Choisir le type de la balle&lt;/strong&gt;',['../index.html#autotoc_md17',1,'']]],
  ['de_20la_20musique_20strong_4',['&lt;strong&gt;Changement de la musique&lt;/strong&gt;',['../index.html#autotoc_md18',1,'']]],
  ['de_20la_20musique_20yanis_20strong_5',['&lt;strong&gt;Changement de la musique [Yanis]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['de_20lancement_6',['de lancement',['../index.html#autotoc_md5',1,'Instructions de lancement'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md86',1,'Instructions de lancement']]],
  ['dec_7',['DEC',['../_c_make_c_x_x_compiler_id_8cpp.html#ad1280362da42492bbc11aa78cbf776ad',1,'CMakeCXXCompilerId.cpp']]],
  ['def_20dounia_8',['Abstraction + Def [Dounia]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]],
  ['def_20suffit_20pas_20dounia_9',['Fonctions lambda + Explication c&apos;est quoi en relaite (def suffit pas) [Dounia]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md71',1,'']]],
  ['def_20vasilis_10',['Def Vasilis',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md72',1,'Encapsulation + Def [Vasilis]'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md68',1,'Héritage + Def [Vasilis]']]],
  ['def_20yanis_11',['Polymorphisme + Def [Yanis]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md69',1,'']]],
  ['delete_5fhighscore_12',['delete_highscore',['../class_saving.html#a6faaf9d491dcf4ae1f60366b8415dad8',1,'Saving']]],
  ['delete_5fsave_13',['delete_save',['../class_saving.html#a165e2c1effaaf2c94eafb38341b1cad6',1,'Saving']]],
  ['demo_14',['PENDANT LA DEMO',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md83',1,'']]],
  ['demo_20_3a_20vasilis_15',['Compilation [pendant la demo : Vasilis]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md84',1,'']]],
  ['des_20classes_20du_20jeu_16',['UML – Modélisation des classes du jeu',['../index.html#autotoc_md39',1,'']]],
  ['des_20données_20strong_17',['&lt;strong&gt;Chiffrement des données&lt;/strong&gt;',['../index.html#autotoc_md19',1,'']]],
  ['des_20données_20vasilis_20strong_18',['&lt;strong&gt;Chiffrement des données [Vasilis]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['des_20pages_20strong_19',['&lt;strong&gt;Structure des pages&lt;/strong&gt;',['../index.html#autotoc_md22',1,'']]],
  ['des_20tests_20',['Organisation des tests',['../index.html#autotoc_md34',1,'']]],
  ['diapo_201_20logo_21',['L&apos;objectif [Yanis] - Diapo 1 (logo)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['diapo_202_20un_20jue_20lequel_22',['Le jeu [Yanis] - Diapo 2 (Un jue, lequel)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['diapo_203_20ou_23',['Les différents modes - Diapo 3 ou +++',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['diapo_204_24',['Fonctionalites (Les petits plus) - Diapo 4',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['diapo_205_20strong_25',['&lt;strong&gt;Les objets [1. Yanis, 2. Dounia, 3. Vasilis ] - Diapo 5&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md63',1,'']]],
  ['diapo_206_20strong_26',['&lt;strong&gt;Les concepts clés - Diapo 6&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['diapo_207_27',['Problemes recnontres [Dounia] - Diapo 7',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md76',1,'']]],
  ['diapo_208_28',['Pour aller plus loin [Vasilis] - Diapo 8',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'']]],
  ['diapo_209_29',['Conclusion [Yanis] - Diapo 9',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md80',1,'']]],
  ['différents_20modes_30',['Les différents modes',['../index.html#autotoc_md8',1,'']]],
  ['différents_20modes_20diapo_203_20ou_31',['Les différents modes - Diapo 3 ou +++',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['documentation_32',['Documentation',['../index.html#autotoc_md6',1,'']]],
  ['données_20strong_33',['&lt;strong&gt;Chiffrement des données&lt;/strong&gt;',['../index.html#autotoc_md19',1,'']]],
  ['données_20vasilis_20strong_34',['&lt;strong&gt;Chiffrement des données [Vasilis]&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['dounia_35',['Dounia',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'Abstraction + Def [Dounia]'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md71',1,'Fonctions lambda + Explication c&apos;est quoi en relaite (def suffit pas) [Dounia]'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'Storytime mode [Dounia]']]],
  ['dounia_203_20vasilis_20diapo_205_20strong_36',['&lt;strong&gt;Les objets [1. Yanis, 2. Dounia, 3. Vasilis ] - Diapo 5&lt;/strong&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md63',1,'']]],
  ['dounia_20diapo_207_37',['Problemes recnontres [Dounia] - Diapo 7',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md76',1,'']]],
  ['dounia_20strong_38',['Dounia strong',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'&lt;strong&gt;Choisir le type de la balle [Dounia]&lt;/strong&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'&lt;strong&gt;Fun mode [Dounia]&lt;/strong&gt;']]],
  ['down_5fpressed_39',['down_pressed',['../struct_paddle_state.html#abe1a41ff6ae93404335fcf4f9d755c9d',1,'PaddleState']]],
  ['drawfilledcircle_40',['DrawFilledCircle',['../structcircle__renderer.html#ac40e4afb68f757ae34434ed4823a22f4',1,'circle_renderer::DrawFilledCircle()'],['../classic__ball_8cpp.html#a51e1c0f7fcd3e2b45855d8b851db3bc8',1,'DrawFilledCircle():&#160;classic_ball.cpp']]],
  ['du_20développement_41',['Autres aspects du développement',['../index.html#autotoc_md32',1,'']]],
  ['du_20jeu_42',['UML – Modélisation des classes du jeu',['../index.html#autotoc_md39',1,'']]],
  ['du_20jeu_20strong_43',['&lt;strong&gt;La logique du jeu&lt;/strong&gt;',['../index.html#autotoc_md23',1,'']]],
  ['duration_5feffect_44',['duration_effect',['../class_power.html#a29c7807215ab51efecde6056541a5b77',1,'Power']]]
];
